version: '3.9'

services:

#  redis:
#    container_name: redis
#    image: redis:7
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./redis:/data

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
      POSTGRES_DB: "test-db"

  back:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
      - /app/node_modules
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    env_file:
      - ./front/.env.development
    volumes:
      - ./front:/app
      - /app/node_modules
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - back
